### ISSUE TITLE
Design Changes

### ISSUE THREAD

**Issue by DavidKozdra** [0ME9A/compressy#1]
![image](https://github.com/0ME9A/compressy/assets/45106564/4c49b1f5-8791-4d99-aa18-27d19025449e)

I find this design a little noisy 

I love the leaf Icon 

Light mode also has issues mostly both seem to have issues with the nav bar glow or shadow that is under it
the icon also needs a border or some way of to pop above the navbar 
![image](https://github.com/0ME9A/compressy/assets/45106564/b80d9794-0813-4439-b990-39fcfa76d666)

I like the blue wave footer but not sure how it helps of affects the theme, maybe a pile of leaves would be better

**Comment by jaas666** [comment]
I think it looks good. The only thing I'd change is to make the heading solid instead of transparent, and add a more noticeable shadow to the bottom of it so it looks like the heading is always floating above the page. 🪙🪙
