### ISSUE TITLE
Set footer copyright date to current year

### ISSUE THREAD

**Issue by jaas666** [0ME9A/compressy#2]
I think it'll be a good quality of life improvement to have the year automatically set to the current year so it's one less chore to perform manually.

For example, the copyright year right know is set to 2022.

**Comment by 0ME9A** [comment]
👋 Hi @jaas666,

Thank you for taking the time to contribute! Your suggestion for automatically updating the copyright year is a great quality-of-life improvement. I appreciate your attention to detail.

I completely agree that automating the process will make maintenance smoother. I'll work on implementing this enhancement to ensure the copyright year is always up-to-date without any manual intervention.

Stay tuned for updates, and feel free to contribute more ideas or provide further feedback.

Best regards,
@0ME9A
