### ISSUE TITLE
Bulk Image Compression

### ISSUE THREAD

**Issue by 0ME9A** [0ME9A/compressy#4]
# Bulk Image Compression

### **Description:**
As a user of Compressy, I often find myself needing to compress multiple images at once. This would be a valuable feature to enhance user efficiency and convenience.

**User Story:**
As a user, I want the ability to upload and compress multiple images simultaneously so that I can save time and streamline the compression process.

**Expected Features:**
- Allow users to select and upload multiple images in one go.
- Implement a batch processing mechanism to compress each uploaded image.
- Provide clear feedback on the compression progress for each image.
- Download all compressed images as a single ZIP file.

**Additional Context:**
This feature could greatly benefit users who need to compress a set of images for various projects or purposes. It aligns with the goal of making Compressy a versatile and user-friendly tool for image optimization.

**Acceptance Criteria:**
- Users can select multiple images for compression.
- The compression process handles each image independently.
- A clear download option for all compressed images in a ZIP file.

**Note:**
This issue is open for discussion. Contributors and community members are encouraged to share their thoughts, suggestions, or volunteer to take on the implementation.

**Comment by kishore881** [comment]
any ideas on the preview design when multiple images are selected..? a carousel..? smaller previews in a grid fashion..?

**Comment by 0ME9A** [comment]
👋 Hi @kishore881,

Great to see your interest in the Bulk Image Compression feature! When it comes to the preview design for multiple selected images, a grid fashion with smaller previews sounds like a practical and visually appealing approach.

A grid format can provide users with a quick overview of their selected images, and smaller previews would allow them to see more images at once without overwhelming the interface. It aligns well with the goal of streamlining the user experience for compressing multiple images.

I'm open to exploring different design options, so if you have specific ideas or preferences, feel free to share them. Your input is valuable in shaping the feature and ensuring it meets the needs of our users.

### **Visuales examples**
### Desktop
![Frame 43](https://github.com/0ME9A/compressy/assets/83957658/a49b0a67-b341-4dc8-8c78-e527872f1f75)

### Mobile

![Frame 44](https://github.com/0ME9A/compressy/assets/83957658/02339b2a-1c6f-4d97-bea1-24dd8cbf0fec)


Looking forward to collaborating on this enhancement!

Best regards,
@0ME9A
