### ISSUE TITLE
Rename File to original name + dimensions 

### ISSUE THREAD

**Issue by DavidKozdra** [0ME9A/compressy#5]
setting the name to compressy.png will always get renamed and doesn't tell the user enough,

we should rename it to its oldname_width_height

**Comment by 0ME9A** [comment]
👋 Hi @DavidKozdra,

Thanks for your thoughts on the file naming convention. My idea to include the brand name, original file name, width, and height in the new filename is insightful. If you have any other preferences for the filename format, please share.

Keeping the brand name (Compressy) in the filename helps users associate the compressed image with the tool. Including the original file name, width, and height adds context and makes filenames more informative.

Your input is crucial in improving the user experience. Feel free to share any specific details or preferences you have for the naming structure.

I look forward to your continued involvement!

Best,
@0ME9A
